services:
  server:
    build:
      context: ./server
    env_file:
      - /server/.env
    container_name: server
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "80:80"
    stdin_open: true
    tty: true
