services:
  backend:
    build:
      context: ./server
    env_file:
      - /server/.env
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "80:80"
    stdin_open: true
    tty: true
