services:
  backend:
    build:
      context: ./server
    env_file:
      - /server/.env
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/server

  frontend:
    build:
      context: ./client
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    volumes:
      - ./client:/client
      - /client/node_modules
    stdin_open: true
    tty: true
